config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mail_serv.urls", namespace="mail_serv")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    BlockUserView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    UnblockUserView,
    UserCreateView,
    UserListView,
    email_verification,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password_reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path(
        "password_reset_confirm/<str:token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("users/block/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "users/unblock/<int:user_id>/", UnblockUserView.as_view(), name="unblock_user"
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Модель пользователя"""

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    token = models.CharField(
        max_length=100, verbose_name="Token", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [("can_block_service_users", "Can block service users")]

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm, UserCreationForm

from mail_serv.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации пользователя"""

    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class CustomSetPasswordForm(StyleFormMixin, SetPasswordForm):
    """Форма смены пароля"""

    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=True,
        help_text="Пароль должен содержать как минимум 8 символов.",
    )
    new_password2 = forms.CharField(
        label="Подтверждение пароля",
        strip=False,
        required=True,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text="Введите тот же пароль, что и выше.",
    )

users/views.py
import secrets

from django.contrib.auth import login
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, View

from config.settings import EMAIL_HOST_USER
from users.forms import CustomSetPasswordForm, UserRegisterForm
from users.models import User


class UserCreateView(CreateView):
    """Представление для создания нового пользователя."""

    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Подтвердите регистрацию на {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )

        group = Group.objects.get(name="Пользователь")
        group.user_set.add(user)

        return super().form_valid(form)


def email_verification(request, token):
    """Функция для подтверждения email пользователя."""
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class PasswordResetRequestView(View):
    """Представление для запроса сброса пароля пользователя."""

    template_name = "users/password_reset_form.html"
    success_url = "users:login"

    def get(self, request):
        """Функция для получения формы сброса пароля."""
        token = request.GET.get("token")
        if token:
            user = get_object_or_404(User, token=token)
            if user:
                form = CustomSetPasswordForm(user)
                return render(request, self.template_name, {"form": form})
            else:
                return HttpResponse("Invalid token")
        else:
            form = PasswordResetForm()
            return render(request, self.template_name, {"form": form})

    def post(self, request):
        """Функция для отправки запроса на сброс пароля."""
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            user = get_object_or_404(User, email=form.cleaned_data["email"])
            if user:
                token = secrets.token_hex(16)
                user.token = token
                user.save()
                host = request.get_host()
                url = f"http://{host}/users/password_reset_confirm/{token}/"
                send_mail(
                    subject="Подтверждение сброса пароля",
                    message=f"Нажмите на ссылку для сброса пароля: {url}",
                    from_email="ng_nl01@mail.ru",
                    recipient_list=[user.email],
                )
                return redirect("users:login")
        return render(request, self.template_name, {"form": form})


class PasswordResetConfirmView(View):
    """Представление для подтверждения сброса пароля пользователя."""

    template_name = "users/password_reset_confirm.html"
    form_class = CustomSetPasswordForm

    def get(self, request, token):
        user = get_object_or_404(User, token=token)
        if not default_token_generator.check_token(user, token):
            return render(request, self.template_name, {"error": "Истекший токен"})
        else:
            form = self.form_class(initial={"email": user.email})
            return render(request, self.template_name, {"form": form})

    def post(self, request, token):
        """Функция для подтверждения сброса пароля пользователя."""
        user = get_object_or_404(User, token=token)
        if request.method == "POST":
            form = CustomSetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                login(request, user)
                return redirect("users:login")
        else:
            form = CustomSetPasswordForm(user)
        context = {
            "form": form,
        }
        return render(request, "users/password_reset_confirm.html", context)


class UserListView(ListView):
    """Представление для отображения списка пользователей."""

    model = User
    template_name = "users/user_list.html"
    context_object_name = "users"

    def get_queryset(self):
        """Функция для получения списка пользователей с сортировкой."""
        return User.objects.all().order_by("id")


class BlockUserView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """Представление для блокировки пользователя."""

    permission_required = "users.can_block_service_users"

    def post(self, request, **kwargs):
        """Функция для блокировки пользователя."""
        user_id = kwargs.get("user_id")
        if not user_id:
            return HttpResponseBadRequest("Не передан ID пользователя")

        user_to_block = get_object_or_404(User, pk=user_id)

        if user_to_block.id == request.user.id:
            return HttpResponseBadRequest("Нельзя заблокировать самого себя")

        user_to_block.is_active = False
        user_to_block.save()

        return redirect("users:user_list")


class UnblockUserView(LoginRequiredMixin, PermissionRequiredMixin, View):
    """Представление для разблокировки пользователя."""

    permission_required = "users.can_block_service_users"

    def post(self, request, **kwargs):
        """Функция для разблокировки пользователя."""
        user_id = kwargs.get("user_id")
        if not user_id:
            return HttpResponseBadRequest("Не передан ID пользователя")

        user_to_unblock = get_object_or_404(User, pk=user_id)

        if user_to_unblock.id == request.user.id:
            return HttpResponseBadRequest("Нельзя разблокировать самого себя")

        user_to_unblock.is_active = True
        user_to_unblock.save()

        return redirect("users:user_list")

users/templates/users/password_reset_confirm.html
{% extends "mail_serv/base.html" %}
{% block content %}
<div class="container">
    <div class="col-6">
        <div class="card">
            <h2>Сброс пароля</h2>
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Сменить пароль</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends "mail_serv/base.html" %}
{% block content %}
<div class="container">
    <form method="post">
        <div class="col-6">
            <div class="card">
                <h4 class="card-header">Введите почту для восстановления пароля</h4>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить письмо</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends "mail_serv/base.html" %}
{% block content %}
<div class="container">
    <form method="post">
        <div class="col-6">
            <div class="card">
                <h2 class="card-header">Регистрация</h2>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends "mail_serv/base.html" %}

{% block content %}
{% if 'users.can_block_service_users' in perms %}
  <div class="col-lg-3 order-md-last position-fixed" style="margin-left:45px; margin-top:20px; overflow: auto; max-height: 500px">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-primary">Пользователи</span>
    </h4>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th>ID</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
              <td>{{ user.id }}</td>
              <td>{{ user.email }}</td>
              <td style="text-align: right;">
                  {% if not user.is_active %}
                    <form action="{% url 'users:unblock_user' user.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success btn-sm">Разблокировать</button>
                    </form>
                  {% else %}
                    <form action="{% url 'users:block_user' user.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm">Заблокировать</button>
                    </form>
                  {% endif %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="2" class="text-center">Нет пользователей</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endif %}
{% endblock %}