config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mail_serv.urls", namespace="mail_serv")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mail_serv/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mail_serv.views import (
    DisableMailingView,
    EmailSendingAttemptListView,
    MailingCreateView,
    MailingDeleteView,
    MailingDetailView,
    MailingSendView,
    MailingUpdateView,
    MessageManagementCreateView,
    MessageManagementDeleteView,
    MessageManagementDetailView,
    MessageManagementUpdateView,
    RecipientCreateView,
    RecipientDeleteView,
    RecipientDetailView,
    RecipientUpdateView,
    RecipientView,
    home,
)

app_name = "mail_serv"

urlpatterns = [
    path("", home, name="home"),
    path("profile/", RecipientView.as_view(), name="profile"),
    path("mail_serv/create/", RecipientCreateView.as_view(), name="rec_create"),
    path("mail_serv/update/<int:pk>", RecipientUpdateView.as_view(), name="rec_update"),
    path("mail_serv/delete/<int:pk>", RecipientDeleteView.as_view(), name="rec_delete"),
    path(
        "mail_serv/detail/<int:pk>",
        cache_page(60)(RecipientDetailView.as_view()),
        name="rec_detail",
    ),
    path(
        "mail_serv/man_create/",
        MessageManagementCreateView.as_view(),
        name="management_create",
    ),
    path(
        "mail_serv/man_update/<int:pk>",
        MessageManagementUpdateView.as_view(),
        name="management_update",
    ),
    path(
        "mail_serv/man_delete/<int:pk>",
        MessageManagementDeleteView.as_view(),
        name="management_delete",
    ),
    path(
        "mail_serv/man_detail/<int:pk>",
        cache_page(60)(MessageManagementDetailView.as_view()),
        name="management_detail",
    ),
    path("mail_serv/mail_create/", MailingCreateView.as_view(), name="mail_create"),
    path(
        "mail_serv/mail_detail/<int:pk>",
        cache_page(60)(MailingDetailView.as_view()),
        name="mail_detail",
    ),
    path(
        "mail_serv/mail_delete/<int:pk>",
        MailingDeleteView.as_view(),
        name="mail_delete",
    ),
    path(
        "mail_serv/mail_update/<int:pk>",
        MailingUpdateView.as_view(),
        name="mail_update",
    ),
    path(
        "mail_serv/send_message/<int:pk>",
        MailingSendView.as_view(),
        name="send_message",
    ),
    path(
        "mail_serv/emailsenading_list/",
        EmailSendingAttemptListView.as_view(),
        name="emailsenading_list",
    ),
    path(
        "mail_serv/statistic/", EmailSendingAttemptListView.as_view(), name="statistic"
    ),
    path(
        "mail_serv/disabling/<int:mailing_id>",
        DisableMailingView.as_view(),
        name="disabling_mailing",
    ),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    BlockUserView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    UnblockUserView,
    UserCreateView,
    UserListView,
    email_verification,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password_reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path(
        "password_reset_confirm/<str:token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("user_list/", UserListView.as_view(), name="user_list"),
    path("users/block/<int:user_id>/", BlockUserView.as_view(), name="block_user"),
    path(
        "users/unblock/<int:user_id>/", UnblockUserView.as_view(), name="unblock_user"
    ),
]

mail_serv/models.py
from django.conf import settings
from django.db import models


class Recipient(models.Model):
    """Модель получателя"""

    email = models.CharField(max_length=100, unique=False)
    initials = models.CharField(max_length=100, verbose_name="Ф.И.О.")
    comment = models.TextField(max_length=150, verbose_name="Комментарий")

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1
    )

    objects = models.Manager()

    class Meta:
        verbose_name = "Получатель"
        verbose_name_plural = "Получатели"

    def __str__(self):
        return self.initials


class MessageManagement(models.Model):
    """Модель сообщений"""

    subject = models.CharField(max_length=100, verbose_name="Тема письма")
    body = models.TextField(max_length=1000, verbose_name="Тело письма")

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1
    )

    objects = models.Manager()

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
        return self.subject


class Mailing(models.Model):
    """Модель рассылок"""

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    started_at = models.DateTimeField(
        null=True, blank=True, verbose_name="Дата запуска"
    )
    ended_at = models.DateTimeField(
        null=True, blank=True, verbose_name="Дата завершения"
    )
    status = models.CharField(
        max_length=10,
        choices=(
            ("Created", "Создана"),
            ("Started", "Запущена"),
            ("Finished", "Завершена"),
        ),
        verbose_name="Статус",
    )
    message = models.ForeignKey(
        MessageManagement, on_delete=models.CASCADE, verbose_name="Сообщение"
    )
    recipients = models.ManyToManyField(Recipient, verbose_name="Получатели")

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1
    )

    objects = models.Manager()

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        permissions = [("can_disable_mailing", "Can disable mailing")]

    def __str__(self):
        return f"Рассылка {self.message}"


class EmailSendingAttempt(models.Model):
    """Модель попыток отправки"""

    datetime = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10, choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")]
    )
    server_response = models.TextField()
    mailing = models.ForeignKey("Mailing", on_delete=models.CASCADE)

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1
    )

    objects = models.Manager()

    def __str__(self):
        return f"Попытка рассылки {self.datetime}"

mail_serv/views.py
import smtplib
import threading
import time

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import (
    HttpResponseBadRequest,
    HttpResponseForbidden,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
    View,
)

from config.settings import EMAIL_HOST_USER
from mail_serv.forms import MailingForm, MessageManagementForm, RecipientForm
from mail_serv.models import EmailSendingAttempt, Mailing, MessageManagement, Recipient
from mail_serv.services import (
    get_mailings_from_cache,
    get_messages_from_cache,
    get_recipients_from_cache,
)


def home(request):
    """Представление для отображения домашней страницы."""
    return render(request, "mail_serv/home.html")


class RecipientView(ListView):
    """Представление для отображения списка получателей."""

    model = Recipient
    template_name = "mail_serv/profile.html"
    context_object_name = "recipients"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.has_perm("mail_serv.can_disable_mailing"):
            context["mailings"] = Mailing.objects.all()
            context["recipients"] = Recipient.objects.all()
            context["messagemanagements"] = MessageManagement.objects.all()
            context["total_messages"] = MessageManagement.objects.count()
            context["total_recipients"] = Recipient.objects.count()
            context["total_mailings"] = Mailing.objects.count()
        else:
            context["mailings"] = Mailing.objects.filter(owner=self.request.user)
            context["recipients"] = Recipient.objects.filter(owner=self.request.user)
            context["messagemanagements"] = MessageManagement.objects.filter(
                owner=self.request.user
            )
            context["total_messages"] = MessageManagement.objects.filter(
                owner=self.request.user
            ).count()
            context["total_recipients"] = Recipient.objects.filter(
                owner=self.request.user
            ).count()
            context["total_mailings"] = Mailing.objects.filter(
                owner=self.request.user
            ).count()
        return context

    def get_queryset(self):
        """'Получение списка получателей из кэша."""
        recipients = get_recipients_from_cache()
        messages = get_messages_from_cache()
        mailings = get_mailings_from_cache()
        return recipients, messages, mailings


class RecipientCreateView(CreateView, LoginRequiredMixin):
    """Представление для создания получателя."""

    model = Recipient
    form_class = RecipientForm

    def get_success_url(self):
        """Получение адреса для перенаправления после создания."""
        return reverse_lazy("mail_serv:profile")

    def form_valid(self, form):
        """'Создание получателя."""
        form.instance.owner = self.request.user
        return super().form_valid(form)


class RecipientUpdateView(UpdateView, LoginRequiredMixin):
    """Представление для обновления получателя."""

    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy("mail_serv:profile")


class RecipientDeleteView(DeleteView, LoginRequiredMixin):
    """Представление для удаления получателя."""

    model = Recipient

    def get_success_url(self):
        """Получение адреса для перенаправления после удаления."""
        return reverse_lazy("mail_serv:profile")

    def delete(self, request, *args, **kwargs):
        """'Удаление получателя."""
        self.object = self.get_object()
        if request.method == "POST":
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(self.request, *args, **kwargs)


class RecipientDetailView(DetailView, LoginRequiredMixin):
    """'Представление для получателя."""

    model = Recipient
    template_name = "mail_serv/recipient_detail.html"
    context_object_name = "recipient"


class MessageManagementCreateView(CreateView, LoginRequiredMixin):
    """'Представление для создания сообщения."""

    model = MessageManagement
    form_class = MessageManagementForm
    success_url = reverse_lazy("mail_serv:profile")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class MessageManagementUpdateView(UpdateView, LoginRequiredMixin):
    """'Представление для обновления сообщения."""

    model = MessageManagement
    form_class = MessageManagementForm

    def get_success_url(self):
        return reverse_lazy("mail_serv:profile")


class MessageManagementDeleteView(DeleteView, LoginRequiredMixin):
    """Представление для удаления сообщения."""

    model = MessageManagement
    success_url = reverse_lazy("mail_serv:profile")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.method == "POST":
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(self.request, *args, **kwargs)


class MessageManagementDetailView(DetailView, LoginRequiredMixin):
    """'Представление для сообщения."""

    model = MessageManagement
    template_name = "mail_serv/message_detail.html"
    context_object_name = "messagemanagement"


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания рассылки."""

    model = Mailing
    form_class = MailingForm
    template_name = "mail_serv/mailing_form.html"
    success_url = reverse_lazy("mail_serv:profile")

    def get_form_kwargs(self):
        """Получает дополнительные аргументы для формы и добавляет текущего пользователя в них."""
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        """'Создание рассылки."""
        form.instance.owner = self.request.user
        mailing = form.save(commit=False)
        mailing.status = "Создана"
        mailing.save()
        return super().form_valid(form)


class MailingDetailView(DetailView, LoginRequiredMixin):
    """Представление для рассылки."""

    model = Mailing
    template_name = "mail_serv/mailing_detail.html"
    context_object_name = "mailing"


class MailingDeleteView(DeleteView, LoginRequiredMixin):
    """Представление для удаления рассылки."""

    model = Mailing
    success_url = reverse_lazy("mail_serv:profile")


class MailingUpdateView(UpdateView, LoginRequiredMixin):
    """Представление для обновления рассылки."""

    model = Mailing
    form_class = MailingForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy("mail_serv:profile")


class MailingSendView(View, LoginRequiredMixin):
    """Представление для отправки рассылки."""

    def post(self, request, pk=None):
        if pk is None:
            pk = request.POST.get("pk")
        mailing = Mailing.objects.get(id=pk)
        mailing.status = "Запущена"
        mailing.save()
        owner = self.request.user
        thread = threading.Thread(target=send_message, args=(mailing.id, owner))
        thread.start()
        return HttpResponseRedirect(reverse_lazy("mail_serv:profile"))


def send_message(mailing_id, owner):
    """'Функция для отправки рассылки."""
    mailing = Mailing.objects.get(id=mailing_id)
    mailing.status = "Запущена"
    mailing.save()
    mailing = Mailing.objects.get(id=mailing_id)
    recipients = mailing.recipients.all()
    end = mailing.ended_at
    current_time = timezone.now()
    if current_time > end:
        mailing.status = "Завершена"
        mailing.save()
        return

    while timezone.now() < end:
        mailing.refresh_from_db()
        if mailing.status == "Завершена":
            break
        else:
            for recipient in recipients:
                try:
                    send_mail(
                        mailing.message.subject,
                        mailing.message.body,
                        from_email=EMAIL_HOST_USER,
                        recipient_list=[recipient.email],
                        fail_silently=False,
                    )
                    EmailSendingAttempt.objects.create(
                        status="Успешно",
                        server_response="Сообщение отправлено",
                        mailing=mailing,
                        owner=owner,
                    )
                except smtplib.SMTPRecipientsRefused as e:
                    print(
                        f"Ошибка при отправке письма, проверьте правильность написания почты: {e}"
                    )
                    EmailSendingAttempt.objects.create(
                        status="Не успешно",
                        server_response="Почты не существует",
                        mailing=mailing,
                        owner=owner,
                    )
                except Exception as e:
                    print(f"Ошибка при отправке письма: {e}")
                    EmailSendingAttempt.objects.create(
                        status="Не успешно",
                        server_response=f"Ошибка при отправке {e}",
                        mailing=mailing,
                        owner=owner,
                    )
            time.sleep(30)

            mailing.status = "Завершена"
            mailing.save()


@method_decorator(cache_page(60 * 15), name="dispatch")

mail_serv/templates/mail_serv/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailstore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom box-shadow" style="background-color: #e3a5a5">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
          <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576zm6.787-8.201L1.591 6.602l4.339 2.76z"/>
        </svg>
        <a href="/"><span class="link-underline-dark">Mailstore</span></a>
    </h5>
    <nav class="ms-3">
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-light" href="/">Главная</a>
            <a class="p-2 btn btn-light" href="{% url 'mail_serv:profile' %}">Профиль</a>
            <a class="p-2 btn btn-light" href="{% url 'mail_serv:statistic' %}">Статистика</a>
            {% if 'users.can_block_service_users' in perms %}
                <a type="button" class="btn btn-warning" href="{% url 'users:user_list' %}">Пользователи</a>
            {% endif %}
        {% else %}
            <a class="p-2 btn btn-light" href="{% url 'users:login' %}?next=/profile/">Вход</a>
        {% endif %}
        <div class="btn-group dropdown" style="margin-left: 1200px">
            <button class="p-2 btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                Пользователь
            </button>
            <ul class="dropdown-menu">
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'users:logout' %}">
                      {% csrf_token %}
                      <button type="submit" style="background-color: black; color: white;">Выйти</button>
                    </form>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.3/js/bootstrap.bundle.min.js">
</script>
</body>
</html>

mail_serv/templates/mail_serv/home.html
{% extends "mail_serv/base.html" %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mailstore</h1>
    <p class="lead highlight">
        <h5>Mailstore - это отличный вариант сохранение старых клиентов и добавление новых участников в вашу команду!</h5>
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-4 h-100">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">Шаг 1</h1>
                </div>
                <div class="card-body bg-danger.bg-gradient mt-3">
                    <h4 class="card-title pricing-card-title">Загрузите базу email-адресов</h4>
                    {% if user.is_authenticated %}
                        <a href="{% url 'mail_serv:rec_create' %}" type="button" class="btn btn-lg btn-block btn-outline-primary mt-1">Перейти</a>
                    {% else %}
                      <div class="alert alert-danger" role="alert">
                        Пожалуйста, войдите в систему, чтобы продолжить.
                      </div>
                      <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-4 h-100">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">Шаг 2</h1>
                </div>
                <div class="card-body mt-4">
                    <h4 class="card-title pricing-card-title">Создайте письмо</h4>
                    {% if user.is_authenticated %}
                        <a href="{% url 'mail_serv:management_create' %}" type="button" class="btn btn-lg btn-block btn-outline-primary mt-4">Создать</a>
                    {% else %}
                      <div class="alert alert-danger" role="alert">
                        Пожалуйста, войдите в систему, чтобы продолжить.
                      </div>
                      <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-4 h-100">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h1 class="my-0 font-weight-normal">Шаг 3</h1>
                </div>
                <div class="card-body mt-0">
                    <h4 class="card-title pricing-card-title">Создайте и запустите рассылку</h4>
                    {% if user.is_authenticated %}
                        <a href="{% url 'mail_serv:mail_create' %}" type="button" class="btn btn-lg btn-block btn-outline-primary mt-4">Запустить</a>
                    {% else %}
                      <div class="alert alert-danger" role="alert">
                        Пожалуйста, войдите в систему, чтобы продолжить.
                      </div>
                      <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mail_serv/templates/mail_serv/mailing_confirm_delete.html
{% extends 'mail_serv/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Вы действительно хотите удалить "{{ mailing.message }}"?</p>
                    <div class="card-body">
                        {% csrf_token %}
                        <a href="{% url 'mail_serv:profile' %}" class="btn btn-primary">Отменить</a>
                        <button type="submit" class="btn btn-primary btn btn-danger">
                            Удалить
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mail_serv/templates/mail_serv/mailing_detail.html
{% extends "mail_serv/base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row mt-5">
    <div class="col-md-6">
      <p>Дата запуска: {{ mailing.started_at }}</p>
      <p>Дата завершения: {{ mailing.ended_at }}</p>
      <p>Сообщение: {{ mailing.message }}</p>
      <p>
          Получатели: {{ mailing.recipients.count }}
      </p>
      <p>Статус: {{ mailing.status }}</p>
      <a href="{% url 'mail_serv:profile' %}" class="btn btn-primary mt-3">Назад на главную</a>
    </div>
  </div>
</div>
{% endblock %}

mail_serv/templates/mail_serv/mailing_form.html
{% extends 'mail_serv/base.html' %}

{% block content %}
  <div class="container">
    <form method="post" class="row g-3">
       <h4 class="mt-3">{% if mailing %}Редактировать рассылку{% else %}Создать рассылку{% endif %}</h4>
      {% csrf_token %}
      <div class="col-md-6">
        <div class="form-group">
          <label for="id_started_at">Начало рассылки:</label>
          <input type="datetime-local" lang="ru" class="form-control" name="started_at" id="id_started_at">
        </div>
        <div class="form-group">
          <label for="id_ended_at">Завершение рассылки:</label>
          <input type="datetime-local" lang="ru" class="form-control" name="ended_at" id="id_ended_at">
        </div>
        {{ form.recipients.label_tag }} (Зажмите Ctrl чтобы выбрать несколько) {{ form.recipients }}
        <div class="mb-3">
          <a href="{% url 'mail_serv:rec_create' %}" class="btn btn-primary btn-sm rounded-pill">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill-add" viewBox="0 0 16 16">
              <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 1 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
              <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
            </svg>
            Добавить получателя
          </a>
        </div>
        {{ form.message.label_tag }} {{ form.message }}
        <a href="{% url 'mail_serv:management_create' %}" class="btn btn-primary btn-sm rounded-pill">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-plus" viewBox="0 0 16 16">
            <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2zm3.708 6.208L1 11.105V5.383zM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2z"/>
            <path d="M16 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0m-3.5-2a.5.5 0 0 0-.5.5v1h-1a.5.5 0 0 0 0 1h1v1a.5.5 0 0 0 1 0v-1h1a.5.5 0 0 0 0-1h-1v-1a.5.5 0 0 0-.5-.5"/>
          </svg>
          Добавить сообщение
        </a>
      </div>
      <div class="col-12 text-center">
      <div class="d-inline-flex align-items-center">
        <button type="submit" class="btn btn-primary mr-3">{% if mailing %} Сохранить {% else %} Создать {% endif %}</button>
        <a href="{% url 'mail_serv:profile' %}" class="btn btn-primary mt-0" style="margin-left: 10px">Вернуться в профиль</a>
      </div>
      </div>
    </form>
  </div>
{% endblock %}